version: '3.4'

volumes:
  jira_data: {}
  jira_db: {}

services:

  jira:
    build: 
      context: .
      dockerfile: provision/Dockerfile
    container_name: idev_jira
    restart: always
    environment:
      - TZ='Europe/Moscow'
    depends_on:
      - mysql
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jira.rule=Host(`jira.idev-present.ru`)"
      - "traefik.http.services.jira.loadbalancer.server.port=8080"
    ports:
      - "8080:8080"
    volumes:
      - jira_data:/var/jira
    networks:
      - idev_network

  mysql:
    image: mysql:5.7
    container_name: idev_jiraDB
    restart: always
    environment:
      - TZ='Europe/Moscow'
      - MYSQL_DATABASE=idev_jiraDB
      - MYSQL_ROOT_PASSWORD=dv3I8QWQ6kgaXI46lbPH
      - MYSQL_USER=idev_jira
      - MYSQL_PASSWORD=dv3I8QWQ6kgaXI46lbPH
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin']
    labels:
      - "traefik.enable=false"
    ports:
      - "13306:3306"
    volumes:
      - jira_db:/var/lib/mysql
    networks:
      - idev_network

  proxy:
    image: traefik:v2.0
    container_name: idev_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.proxy.rule=Host(`proxy.idev-present.ru`)"
      - "traefik.http.routers.proxy.middlewares=auth"
      - "traefik.http.routers.proxy.service=api@internal"
      - "traefik.http.routers.proxy.entrypoints=websecure"
      - "traefik.http.routers.proxy.tls.certresolver=leresolver"
      - "traefik.http.middlewares.auth.basicauth.users=user:$$apr1$$q8eZFHjF$$Fvmkk//V6Btlaf2i/ju5n/"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/acme.json:/acme.json
    networks:
      - default
      - idev_network

networks:
  idev_network:
    external: 
      name: idev_network
  default:
    driver: bridge


    