version: '3.4'

services:

  proxy:
    image: traefik:v2.0
    ports:
      - "80:80"
      # - "8080:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.idev.rule=Host(`proxy.idev-present.ru`)"
      - "traefik.port=8080"
      - "traefik.docker.network=idev_network"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
    networks:
      - default
      - idev_network

networks:
  idev_network:
    external: 
      name: idev_network
  default:
    driver: bridge