version: '3.4'

volumes:
  flow_db: {}

services:

  flow:
    image: herzcthu/bugzilla:latest
    container_name: idev_flow
    restart: always
    depends_on: 
      - mysql
    environment:
      - TZ='Europe/Moscow'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flow.rule=Host(`flow.idev-present.ru`)"
      - "traefik.http.routers.flow.entrypoints=web"
    volumes:
      - ./bugzilla/config:/usr/local/apache2/htdocs/localconfig
      - ./bugzilla/russian/help:/usr/local/apache2/htdocs/help
      - ./bugzilla/russian/template/ru-RU:/usr/local/apache2/htdocs/template/ru-RU
    networks:
      - idev_network

  mysql:
    image: mysql:5.7
    container_name: idev_flowDB
    restart: always
    environment:
      - TZ='Europe/Moscow'
      - MYSQL_DATABASE=bugs
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=bugs
      - MYSQL_PASSWORD=bugs
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin']
    labels:
      - "traefik.enable=false"
    ports: 
      - "13306:3306"
    volumes:
      - flow_db:/var/lib/mysql
    networks:
      - idev_network

  proxy:
    image: traefik:v2.0
    container_name: idev_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.proxy.rule=Host(`proxy.idev-present.ru`)"
      - "traefik.http.routers.proxy.middlewares=auth"
      - "traefik.http.routers.proxy.service=api@internal"
      - "traefik.http.routers.proxy.entrypoints=websecure"
      - "traefik.http.routers.proxy.tls=true"
      - "traefik.http.routers.proxy.tls.certresolver=leresolver"
      - "traefik.http.middlewares.auth.basicauth.users=user:$$apr1$$q8eZFHjF$$Fvmkk//V6Btlaf2i/ju5n/"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/acme.json:/acme.json
    networks:
      - default
      - idev_network

networks:
  idev_network:
    external: 
      name: idev_network
  default:
    driver: bridge


    
