version: '3.4'

services:

  proxy:
    image: traefik:v2.0
    container_name: idev_proxy
    ports:
      - "80:80"
      - "8080:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.proxy.rule=Host(`proxy.idev-present.ru`)"
      # - "traefik.http.services.idev.api.server.port=80"
      - "traefik.http.routers.proxy.service=api@internal"
      - "traefik.http.routers.proxy.middlewares=auth"
      - "traefik.http.middlewares.proxy.basicauth.users=admin:$apr1$CbPtxdgO$R4MpeTYh2ok2.kU7hoxNF1"
      # - "traefik.http.routers.whoami.entrypoints=web"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
    networks:
      - default
      - idev_network

networks:
  idev_network:
    external: 
      name: idev_network
  default:
    driver: bridge