version: '3.4'

services:

  proxy:
    image: traefik:v2.0
    container_name: idev_proxy
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.proxy.rule=Host(`proxy.idev-present.ru`)"
      - "traefik.http.routers.proxy.middlewares=auth"
      - "traefik.http.routers.proxy.service=api@internal"
      - "traefik.http.routers.proxy.entrypoints=websecure"
      - "traefik.http.routers.proxy.tls.certresolver=leresolver"
      - "traefik.http.middlewares.auth.basicauth.users=user:$$apr1$$q8eZFHjF$$Fvmkk//V6Btlaf2i/ju5n/"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/acme.json:/acme.json
    networks:
      - default
      - idev_network

networks:
  idev_network:
    external: 
      name: idev_network
  default:
    driver: bridge