
################################################################
# Global configuration
################################################################
global:
    checkNewVersion: true
    sendAnonymousUsage: true

################################################################
# Entrypoints configuration
################################################################
entryPoints:
    web:
      address: ":80"
  
    websecure:
      address: ":443"

################################################################
# Traefik logs configuration
################################################################

################################################################
# API and dashboard configuration
################################################################
api:
    dashboard: true
        
################################################################
# Ping configuration
################################################################

################################################################
# Docker configuration backend
################################################################
providers:
    docker: {}

