
################################################################
# Global configuration
################################################################
global:
    checkNewVersion: true
    sendAnonymousUsage: true

################################################################
# Entrypoints configuration
################################################################
entryPoints:
    web:
      address: ":80"
  
    websecure:
      address: ":443"

################################################################
# Traefik logs configuration
################################################################

################################################################
# API and dashboard configuration
################################################################
api:
    dashboard: true
    insecure: true

################################################################
# HTTP configuration
################################################################
http:
    routers:
        api:
            rule: Host(`proxy.idev-present.ru`)
            service: api@internal
            middlewares:
                - auth
    middlewares:
        auth:
            basicAuth:
                users:
                    - "admin:$apr1$CbPtxdgO$R4MpeTYh2ok2.kU7hoxNF1"
        
################################################################
# Ping configuration
################################################################

################################################################
# Docker configuration backend
################################################################
providers:
    docker: {}

