
################################################################
# Global configuration
################################################################
global:
    checkNewVersion: true
    sendAnonymousUsage: true

################################################################
# Entrypoints configuration
################################################################
entryPoints:
    web:
      address: ":80"
  
    websecure:
      address: ":443"

################################################################
# Traefik logs configuration
################################################################
log:
    level: DEBUG
################################################################
# API and dashboard configuration
################################################################
api:
    dashboard: true
    insecure: true
    debug: true
        
################################################################
# Ping configuration
################################################################

################################################################
# Docker configuration backend
################################################################
providers:
    docker:
        endpoint: "unix:///var/run/docker.sock"
        network: idev_network
        defaultRule: "Host(`{{ trimPrefix `/` .Name }}.idev-present.ru`)"
